# Active Profile (dev | prod)
spring.profiles.active=dev
spring.profiles.include=secrets

# Server
server.port=8080

# Mustache
spring.mustache.servlet.expose-request-attributes=true
spring.mustache.servlet.expose-session-attributes=true
