# Active Profile (dev | prod)
spring.profiles.active=dev
spring.profiles.include=secrets

# Server
server.port=8080

# Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.mustache.charset=UTF-8

# Mustache
spring.mustache.servlet.expose-request-attributes=true
spring.mustache.servlet.expose-session-attributes=true

# Multipart Upload Settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB

# File Upload Path
file.upload-dir=./upload/

# PortOne V2 Configuration (Replace with real keys in production)
portone.store-id=store-7eca3abb-a8a7-49ee-8416-2e7168e0d54a
portone.channel-key=channel-key-a635ccae-1da9-4442-9f67-c0d063f79f3a
portone.api-secret=SOTKrDcf1PyYmg3nuDbkKZReMhpmbfwWbjAHW0nbzK7HvhwYA4dYUXqRa2LKkfObzZkI8GbwrtB7wCgr
portone.api-url=https://api.portone.io
