# Active Profile (dev | prod)
spring.profiles.active=dev
spring.profiles.include=secrets

# Server
server.port=8080

<<<<<<< HEAD
# 2. H2 Database 설정 (개발 단계)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:campingdb;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. JPA / Hibernate 설정
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# H2 2.x 버전 호환성 설정
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# 3.1 SQL Data Initialization
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:db/testData.sql
spring.jpa.defer-datasource-initialization=true

# 4. Mustache 설정
=======
# Mustache
>>>>>>> 99492c1d3d3dca07c67d1b454c7e8e3371a97993
spring.mustache.servlet.expose-request-attributes=true
spring.mustache.servlet.expose-session-attributes=true
